export const GET_LIST_MOVIE_API = 'GET_LIST_MOVIE_API';
export const GET_LIST_CINEMA_API = "GET_LIST_CINEMA_API";
export const GET_LIST_CINEMA_DETAIL_API = "GET_LIST_CINEMA_DETAIL_API";
export const GET_SHOWTIMES_INFO_API = "GET_SHOWTIMES_INFO_API";
export const VIEW_TRAILER = 'VIEW_TRAILER';
export const SEARCH = "SEARCH";