export const GET_LIST_MOVIE_API = 'GET_LIST_MOVIE_API';
export const GET_DETAIL_MOVIE = "GET_DETAIL_MOVIE";
export const GET_LIST_CINEMA_API = "GET_LIST_CINEMA_API";
export const GET_LIST_CINEMA_DETAIL_API = "GET_LIST_CINEMA_DETAIL_API";
export const GET_SHOWTIMES_INFO_API = "GET_SHOWTIMES_INFO_API";
export const VIEW_TRAILER = 'VIEW_TRAILER';

export const GET_LIST_COMMENT_API = "GET_LIST_COMMENT_API";
export const POST_COMMENT_API = "POST_COMMENT_API";
export const PUT_COMMENT_API = "PUT_COMMENT_API";
export const LOAD_USER = "LOAD_USER";
export const SHOW_LOGIN = "SHOW_LOGIN";